# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtBblDxy1xceoepXTUZVzZGNeSmpZLZS
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_curve, auc, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# ================================
# 1. STREAMLIT SETTINGS
# ================================
st.set_page_config(page_title="IDS Dashboard", layout="wide")

st.title("IDS Dashboard — CICIDS2017")

# ================================
# 2. FILE UPLOADER
# ================================
uploaded_file = st.file_uploader("Upload a cleaned CICIDS2017 CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    # Optionally sample large datasets (for faster demo)
    if len(df) > 100000:
        st.warning("Dataset too large, sampling 100,000 rows for performance.")
        df = df.sample(100000, random_state=42)

    # ================================
    # 3. SEPARATE FEATURES AND LABEL
    # ================================
    X = df.drop(columns=['Label'])
    y = df['Label']

    # ================================
    # 4. TRAIN/TEST SPLIT
    # ================================
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.3,
        random_state=42,
        stratify=y
    )

    # ================================
    # 5. ISOLATION FOREST (UNSUPERVISED)
    # ================================
    iso = IsolationForest(
        contamination=0.1,
        random_state=42
    )
    iso.fit(X_train)
    y_pred_iso = iso.predict(X_test)
    y_pred_iso = np.where(y_pred_iso == -1, "ATTACK", "BENIGN")

    # ================================
    # 6. RANDOM FOREST (SUPERVISED)
    # ================================
    rf = RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )
    rf.fit(X_train, y_train)
    y_pred_rf = rf.predict(X_test)

    # ================================
    # 7. EVALUATION METRICS
    # ================================
    # Reports
    report_iso = classification_report(y_test, y_pred_iso, output_dict=True)
    report_rf  = classification_report(y_test, y_pred_rf, output_dict=True)

    # ROC for RandomForest (use probabilities)
    fpr_rf, tpr_rf, _ = roc_curve(
        y_test.map({'BENIGN':0, 'ATTACK':1}),
        rf.predict_proba(X_test)[:, 1]
    )
    roc_auc_rf = auc(fpr_rf, tpr_rf)

    # ROC for IsolationForest (binary predictions only)
    fpr_iso, tpr_iso, _ = roc_curve(
        y_test.map({'BENIGN':0, 'ATTACK':1}),
        (y_pred_iso == "ATTACK").astype(int)
    )
    roc_auc_iso = auc(fpr_iso, tpr_iso)

    # Confusion matrices
    cm_rf  = confusion_matrix(y_test, y_pred_rf,  labels=['BENIGN','ATTACK'])
    cm_iso = confusion_matrix(y_test, y_pred_iso, labels=['BENIGN','ATTACK'])

    # ================================
    # 8. STREAMLIT DASHBOARD
    # ================================
    model_choice = st.sidebar.radio(
        "Select Model to View",
        ["IsolationForest", "RandomForest", "Comparison"]
    )

    if model_choice == "IsolationForest":
        st.subheader("Isolation Forest (Unsupervised)")
        st.metric("ROC-AUC", f"{roc_auc_iso:.3f}")
        st.write("Classification Report:", pd.DataFrame(report_iso).transpose())

        fig_cm, ax = plt.subplots()
        sns.heatmap(cm_iso, annot=True, fmt="d", cmap="Blues", ax=ax)
        plt.tight_layout()
        st.pyplot(fig_cm)

        fig_roc, ax = plt.subplots()
        ax.plot(fpr_iso, tpr_iso, label=f"AUC = {roc_auc_iso:.3f}")
        ax.plot([0, 1], [0, 1], 'k--')
        ax.set_xlabel("False Positive Rate")
        ax.set_ylabel("True Positive Rate")
        ax.set_title("ROC Curve")
        ax.legend()
        st.pyplot(fig_roc)

    elif model_choice == "RandomForest":
        st.subheader("Random Forest (Supervised)")
        st.metric("ROC-AUC", f"{roc_auc_rf:.3f}")
        st.write("Classification Report:", pd.DataFrame(report_rf).transpose())

        fig_cm, ax = plt.subplots()
        sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Greens", ax=ax)
        plt.tight_layout()
        st.pyplot(fig_cm)

        fig_roc, ax = plt.subplots()
        ax.plot(fpr_rf, tpr_rf, label=f"AUC = {roc_auc_rf:.3f}")
        ax.plot([0, 1], [0, 1], 'k--')
        ax.set_xlabel("False Positive Rate")
        ax.set_ylabel("True Positive Rate")
        ax.set_title("ROC Curve")
        ax.legend()
        st.pyplot(fig_roc)

    else:
        st.subheader("Model Comparison: IsolationForest vs RandomForest")

        col1, col2 = st.columns(2)
        with col1:
            st.write("**Isolation Forest Confusion Matrix**")
            fig_cm, ax = plt.subplots()
            sns.heatmap(cm_iso, annot=True, fmt="d", cmap="Blues", ax=ax)
            plt.tight_layout()
            st.pyplot(fig_cm)
        with col2:
            st.write("**Random Forest Confusion Matrix**")
            fig_cm, ax = plt.subplots()
            sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Greens", ax=ax)
            plt.tight_layout()
            st.pyplot(fig_cm)

        col1, col2 = st.columns(2)
        with col1:
            st.write("**Isolation Forest ROC Curve**")
            fig_roc, ax = plt.subplots()
            ax.plot(fpr_iso, tpr_iso, label=f"AUC = {roc_auc_iso:.3f}")
            ax.plot([0, 1], [0, 1], 'k--')
            ax.legend()
            st.pyplot(fig_roc)
        with col2:
            st.write("**Random Forest ROC Curve**")
            fig_roc, ax = plt.subplots()
            ax.plot(fpr_rf, tpr_rf, label=f"AUC = {roc_auc_rf:.3f}")
            ax.plot([0, 1], [0, 1], 'k--')
            ax.legend()
            st.pyplot(fig_roc)

    # ================================
    # 9. PREDICTIONS TABLE
    # ================================
    pred_df = pd.DataFrame({
        "True Label": y_test,
        "Predicted (RF)": y_pred_rf,
        "Predicted (ISO)": y_pred_iso
    })
    st.subheader("Sample Predictions")
    st.dataframe(pred_df.head(20))
    # Download button
    csv = pred_df.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="📥 Download Predictions as CSV",
        data=csv,
        file_name="predictions.csv",
        mime="text/csv"
    )

else:
    st.info("👆 Please upload a cleaned CICIDS2017 CSV file to start.")